version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: nest-api-nestjs
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "${DATABASE_URL_CONTAINER}"
      CLOUDINARY_CLOUD_NAME: "dva9173ng"
      CLOUDINARY_API_KEY: "822216363879663"
      CLOUDINARY_API_SECRET: "ogqAfYyGqnU2mwGbENRykYleGE84"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
